create table credor (
	identificacao varchar(25) primary key,
	tipo_credor int,
	nome_credor varchar(100),
	insc_estado varchar(50),
	insc_municipio varchar(50),
	cep varchar(25),
	end_comercio varchar(150),
	bairro varchar(100),
	municipio varchar(100),
	uf varchar(5),
	ponto_ref varchar(100),
	tel_comercio varchar(25),
	tel_residencial varchar(25),
	tel_celular varchar(25),
	banco varchar(50),
	agencia varchar(50),
	conta_bancaria varchar(50),
	nome_conta varchar(100),
	email varchar(100),
	foreign key (tipo_credor) references tipo_credor (cod_tcredor));